structure:
  readme: README.md
  summary: SUMMARY.md
  languages: LANGS.md

plugins:
  - html
  - iframe
  - search
  - fontsettings
  - theme-default

pluginsConfig:
  html:
    allowedTags:
      - iframe
      - div
      - script
    allowedAttributes:
      iframe: [src, width, height, frameborder, allowfullscreen, title]
      div: [class, id, style, data-lang]
      script: [src, type]

title: "MumToBe User Guide"
description: "Complete documentation for MumToBe Maternal Health Platform"
author: "MumToBe Team"
language: en

styles:
  website: ./styles/website.css

variables:
  scribehow_base_url: "https://scribehow.com"
  embed_height: "900px"

links:
  github: "https://github.com/mumtobe/mumtobe-docs"
  website: "https://mumtobe.com"
