name: Deploy HonKit

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'package.json' ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # HonKit recommends Node.js 14+; Node 18 is a good LTS choice.

      - name: Install dependencies
        run: npm install

      - name: Build HonKit
        run: npm run build
        working-directory: . # Run from the repository root

      - name: Copy root files
        run: |
          cp index.html docs/_book/
          cp -f index.html docs/_book/index.html
          cp docs/.nojekyll docs/_book/.nojekyll

      - uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
